[package]
name = "fungible-token"
version = "0.1.0"
authors = ["dungdv.cntt@gmail.com"]
edition = "2021"

crate-type = ["cdylib", "rlib"]

[dependencies]
near-sdk = "3.1.0"
near-contract-standards = "3.2.0"

